"""Tests for the friction-table rewriter, :meth:`TelemacModel.tbl_creator`.

This is the function that applies a sampled roughness to a TELEMAC ``.tbl`` before
every calibration run, so anything that makes it raise stops a calibration at its
first evaluation - after the design has been sampled but before a single useful
model output exists.
"""
import pytest

pytest.importorskip("tqdm")

from hydroBayesCal.telemac.control_telemac import TelemacModel


TABLE = """\
* Friction data file generated by axqua
* Columns: Fric_ID  BottomLaw  Coefficient  Mdef
*
* zone 1: roughness zone 1
1\tNIKU\t0.1550\tNULL
* zone 2: roughness zone 2
2\tNIKU\t0.5000\tNULL
END
"""


def _write(tmp_path, text):
    path = tmp_path / "friction.tbl"
    path.write_text(text)
    return path


def test_the_named_zone_is_rewritten_and_the_others_are_not(tmp_path):
    path = _write(tmp_path, TABLE)
    TelemacModel.tbl_creator("1", 0.2718, str(path))
    lines = path.read_text().splitlines()

    assert any(line.startswith("1\t") and "0.2718" in line for line in lines)
    assert any(line.startswith("2\t") and "0.5000" in line for line in lines), \
        "an unrelated zone must keep its coefficient"
    assert lines[-1].strip() == "END"


def test_a_blank_line_does_not_raise(tmp_path):
    """A blank line splits to an empty list, and indexing it used to raise
    IndexError - killing the calibration on its first parameter rewrite rather than
    at the end. Hand-edited tables routinely carry a trailing or separating blank
    line, so this has to be survivable."""
    with_blanks = TABLE.replace("* zone 2", "\n* zone 2") + "\n\n"
    path = _write(tmp_path, with_blanks)

    TelemacModel.tbl_creator("2", 0.4242, str(path))  # must not raise

    text = path.read_text()
    assert "0.4242" in text
    assert "0.1550" in text, "the untouched zone must survive the rewrite"


def test_a_zone_that_is_not_present_leaves_the_table_alone(tmp_path):
    path = _write(tmp_path, TABLE)
    before = path.read_text()
    TelemacModel.tbl_creator("7", 0.9, str(path))
    assert path.read_text() == before
