"""Tests for the friction-table rewriter, :meth:`TelemacModel.tbl_creator`.

This is the function that applies a sampled roughness to a TELEMAC ``.tbl`` before
every calibration run, so anything that makes it raise stops a calibration at its
first evaluation - after the design has been sampled but before a single useful
model output exists.
"""
import pytest

pytest.importorskip("tqdm")

from hydroBayesCal.telemac.control_telemac import TelemacModel


TABLE = """\
* Friction data file generated by axqua
* Columns: Fric_ID  BottomLaw  Coefficient  Mdef
*
* zone 1: roughness zone 1
1\tNIKU\t0.1550\tNULL
* zone 2: roughness zone 2
2\tNIKU\t0.5000\tNULL
END
"""


def _write(tmp_path, text):
    path = tmp_path / "friction.tbl"
    path.write_text(text)
    return path


def test_the_named_zone_is_rewritten_and_the_others_are_not(tmp_path):
    path = _write(tmp_path, TABLE)
    TelemacModel.tbl_creator("1", 0.2718, str(path))
    lines = path.read_text().splitlines()

    assert any(line.startswith("1\t") and "0.2718" in line for line in lines)
    assert any(line.startswith("2\t") and "0.5000" in line for line in lines), \
        "an unrelated zone must keep its coefficient"
    assert lines[-1].strip() == "END"


def test_a_blank_line_does_not_raise(tmp_path):
    """A blank line splits to an empty list, and indexing it used to raise
    IndexError - killing the calibration on its first parameter rewrite rather than
    at the end. Hand-edited tables routinely carry a trailing or separating blank
    line, so this has to be survivable."""
    with_blanks = TABLE.replace("* zone 2", "\n* zone 2") + "\n\n"
    path = _write(tmp_path, with_blanks)

    TelemacModel.tbl_creator("2", 0.4242, str(path))  # must not raise

    text = path.read_text()
    assert "0.4242" in text
    assert "0.1550" in text, "the untouched zone must survive the rewrite"


def test_a_zone_that_is_not_present_leaves_the_table_alone(tmp_path):
    path = _write(tmp_path, TABLE)
    before = path.read_text()
    TelemacModel.tbl_creator("7", 0.9, str(path))
    assert path.read_text() == before


# --------------------------------------------------------------------------- #
# the roughness diagnostic now runs on the default calibration path
# --------------------------------------------------------------------------- #
import numpy as np

from hydroBayesCal.function_pool import diagnose_roughness_identifiability

QUANTITIES = ["WATER DEPTH", "SCALAR VELOCITY"]


@pytest.mark.parametrize("name, outputs, observations", [
    ("ragged", np.zeros((5, 20)), np.zeros(13)),
    ("empty", np.zeros((0, 20)), np.zeros(20)),
    ("all nan", np.full((5, 20), np.nan), np.zeros(20)),
])
def test_the_diagnostic_never_raises_on_unusable_input(name, outputs, observations):
    """It is report-only and runs after the initial design has cost hours of solver
    time, so bad input must produce a verdict of 'unavailable' - never an exception
    that would discard the completed runs."""
    result = diagnose_roughness_identifiability(outputs, observations, QUANTITIES)
    assert result["verdict"] == "unavailable"
    assert "skipped" in result["message"]


def test_a_single_dead_location_does_not_void_the_verdict():
    """One dry or failed calibration point used to turn the median residual into NaN
    and with it the whole diagnosis."""
    outputs = np.ones((5, 20))
    outputs[:, 7] = np.nan
    result = diagnose_roughness_identifiability(outputs, np.ones(20), QUANTITIES)
    assert result["verdict"] != "unavailable"
    assert np.isfinite(result["depth_residual"])


def test_correlated_residuals_report_roughness_as_non_identifiable():
    """Both quantities over-predicted cannot be produced by roughness alone, so the
    verdict must say so rather than recommend a direction to move ks."""
    observations = np.ones(20)
    outputs = np.full((5, 20), 1.5)          # too deep AND too fast
    result = diagnose_roughness_identifiability(outputs, observations, QUANTITIES)
    assert result["verdict"] == "not_identifiable"
    assert result["identifiable"] is False
