#!/usr/bin/env bash
# Regenerate the auto-generated large-file section of .gitignore.
#
# Files larger than the size limit (20 MB) are excluded from git so that
# example folders can be tracked without pushing big binary data. Run this
# script from anywhere inside the repository after adding new (example) data,
# then commit the updated .gitignore:
#
#   bash env-scripts/update-large-file-ignores.sh
#
# The same limit is enforced for all contributors by the pre-commit hook
# (.pre-commit-config.yaml) and the size-check GitHub Actions workflow.

set -euo pipefail

SIZE_LIMIT_BYTES=$((20 * 1024 * 1024))  # 20 MB
BEGIN_MARK="# >>> large-files (auto-generated by env-scripts/update-large-file-ignores.sh)"
END_MARK="# <<< large-files"

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

gitignore=".gitignore"

# Collect repository files above the size limit (excluding .git itself).
large_files=$(find . -type f -size +${SIZE_LIMIT_BYTES}c \
    -not -path "./.git/*" \
    | sed 's|^\./||' | LC_ALL=C sort)

# Remove a previously generated section.
if grep -qF "$BEGIN_MARK" "$gitignore"; then
    sed -i "\|^$BEGIN_MARK\$|,\|^$END_MARK\$|d" "$gitignore"
fi

{
    echo "$BEGIN_MARK"
    echo "# Files larger than 20 MB stay out of git - do not edit by hand."
    if [ -n "$large_files" ]; then
        echo "$large_files"
    fi
    echo "$END_MARK"
} >> "$gitignore"

count=$(echo -n "$large_files" | grep -c . || true)
echo "Wrote $count large-file ignore entries to $gitignore"

# Warn about files that are already tracked despite exceeding the limit.
tracked_large=$(echo "$large_files" | while read -r f; do
    [ -n "$f" ] && git ls-files --error-unmatch "$f" >/dev/null 2>&1 && echo "$f"
done || true)

if [ -n "$tracked_large" ]; then
    echo "WARNING: these tracked files exceed the 20 MB limit;"
    echo "         remove them with 'git rm --cached <file>':"
    echo "$tracked_large"
fi
