#!/usr/bin/env python3
# this script was auto-generated by HyBayesCal and can be deleted
import sys
sys.path.append('/home/schwindt/github/hybayescal/examples/donau')
from telapy.api.t2d import Telemac2d

try:
    from mpi4py import MPI
    comm = MPI.COMM_WORLD
except:
    comm = None

tXd = Telemac2d('/home/schwindt/github/hybayescal/examples/donau/t2d-donau-const-n.cas', comm=comm, stdout=6)
comm.Barrier()
tXd.set_case()
tXd.set('MODEL.RESULTFILE', 'r2d-donau.slf')
tXd.init_state_default()

comm.Barrier()
tXd.run_all_time_steps()
comm.Barrier()

tXd.finalize()
comm.Barrier()
del(tXd)
