#!/usr/bin/env python3
# this script was auto-generated by HyBayesCal and can be deleted
import sys
sys.path.append('/home/amintvm/modeling/hybayescal/simulationxxx/')
from telapy.api.t2d import Telemac2d

try:
    from mpi4py import MPI
    comm = MPI.COMM_WORLD
except:
    comm = None

tXd = Telemac2d('/home/amintvm/modeling/hybayescal/simulationxxx//t2d-donau-4.cas', comm=comm, stdout=6)
tXd.set_case()
tXd.set('MODEL.RESULTFILE', 'r2d-donau-4.slf')
tXd.init_state_default()

tXd.run_all_time_steps()

tXd.finalize()
del(tXd)
